### ISSUE TITLE
You are weird

### ISSUE THREAD

**Issue by luvhalvorson** [aesophor/py-todo#10]
and I'm cute 🎉

**Comment by aesophor** [comment]
![lolcat](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.qGT0oXW9_ES6FTlq0BbIiwHaFi%26pid%3D15.1&f=1)

**Comment by luvhalvorson** [comment]
QQQQ we are not friends anymore!

**Comment by Steampunkery** [comment]
This is hands down the best written issue I've ever seen. An absolute beauty; masterful prose.
