### ISSUE TITLE
Org-mode TODO test file

### ISSUE THREAD

**Issue by Steampunkery** [aesophor/py-todo#16]
@aesophor I assume because you added an org-mode feature, that you use emacs or have some use for parsing org-mode TODO files. Can you post an example one that I can use for testing changes I made that pertain to org-mode? I don't use emacs, but that won't stop me from improving code :smiley:

**Comment by aesophor** [comment]
Thanks for helping me out! Actually I don't use emacs :laughing:. Org-mode was added initially by @MMarinov97 in cc23aa901ef4fa0a019b99331c07996d4a27cfa5. Maybe we can ask @MMarinov97 or @diplozoon to post an example org-mode file?

**Comment by RewoundVHS** [comment]
GitHub markdown automatically converts the items to check boxes so [here](https://pastebin.com/ucWBwf6v) is a raw paste of an org file I used a few weeks ago.

**Comment by Steampunkery** [comment]
Thanks man! Will use this for testing sub-lists as well

**Comment by RewoundVHS** [comment]
@aesophor You can probably close this.
