### ISSUE TITLE
Problem with color=true in config file

### ISSUE THREAD

**Issue by jolupa** [aesophor/py-todo#17]
Hi!
I downloaded de latest version in github, manually, and when I enabled color = true in config file I encounter the next error:
`Traceback (most recent call last):
  File "/home/jolupa/.local/bin/todo", line 167, in <module>
    list_items()
  File "/home/jolupa/.local/bin/todo", line 94, in list_items
    date = '(' + item.__str__().split('(')[1]
`
If I disable the color entry in the config file the problem disappears.
Thanks

**Comment by RewoundVHS** [comment]
I did some testing and found this was caused by an oversight of mine. I didn't validate for items that did not have dates. I will issue a pull request with the solution to this bug. My apologies!

**Comment by jolupa** [comment]
Fixed! Thanks!
