### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by RewoundVHS** [aesophor/py-todo#7]
Could you add a license file? I am writing a package for the AUR and it is frowned upon to not have a license.

**Comment by aesophor** [comment]
I've added a license. Thank your for writing the AUR package for this!!

**Comment by RewoundVHS** [comment]
No problem! You could possibly add a note to the Readme about how it’s available on the [AUR](https://aur.archlinux.org/packages/py-todo)

**Comment by aesophor** [comment]
Thanks! I've updated README.md
